Add support for provisioning from a boot ISO image
oracle/ol-sample-scripts pull request #29
Opened 2020-10-17 16:25 UTC by AmedeeBulle

This PR allows provisioning from a boot ISO image.

It also enables btrfs root filesystem which will be supported as from Oracle Linux 8 Update 3.

--
Signed-off-by: Philippe Vanhaesendonck <philippe.vanhaesendonck@oracle.com>

2020-10-17 21:40 UTC, Djelibeybi requested changes

2020-10-17 21:40 UTC, Djelibeybi commented on oracle-linux-image-tools/README.md
> +ISO_URL="http://yum.oracle.com/ISOS/OracleLinux/OL8/u2/x86_64/x86_64-boot-uek.iso"
Shouldn't this use `https`?

2020-10-17 21:40 UTC, Djelibeybi commented on oracle-linux-image-tools/README.md
> +REPO_URL="http://yum.oracle.com/repo/OracleLinux/OL8/baseos/latest/x86_64"
Shouldn't this use `https`?

2020-10-17 21:40 UTC, Djelibeybi commented on oracle-linux-image-tools/README.md
>  As user you should only make changes in your local `env.properties` where you can override any definition from the previous property files.
I would rewrite this to "Changes should be made to a local `env.properties` file which can override any definition made in an upstream property file."

2020-10-17 21:40 UTC, Djelibeybi commented on oracle-linux-image-tools/distr/ol8-slim/image-scripts.sh
> +"
We should match the partitioning table used by Anaconda when `btrfs` is selected, add a subvolume  for `/home` as well:

```
btrfs /home --subvol --name=home btr_pool
```

2020-10-17 21:40 UTC, Djelibeybi commented on oracle-linux-image-tools/distr/ol8-slim/image-scripts.sh
> +btrfs none --label=btr_pool --data=single btrfs.01\n\
`btr` is not a suitable shortened term and `pool` isn't a term used with `btrfs` either. If we can't use the default label of `ol_${hostname}`, I suggest using `btrfs_vol` as the terms `volume` and `subvolume` are used with btrfs.

2020-10-17 21:40 UTC, Djelibeybi commented on oracle-linux-image-tools/env.properties
> +# REPO_URL="http://yum.oracle.com/repo/OracleLinux/OL8/baseos/latest/x86_64"
We should provide `https`-based examples.

2020-10-18 09:15 UTC, AmedeeBulle commented
@Djelibeybi `https` URLs fixed (I always get caught by pasting URLs from the public yum which isn't https by default...)

Creating a separate partition/subvolume for `/home` needs more work as this generates regressions elsewhere...

2020-10-18 19:07 UTC, Djelibeybi commented
> Creating a separate partition/subvolume for `/home` needs more work as this generates regressions elsewhere...

How does creating a subvolume for `/home` cause a regression elsewhere?

2020-10-19 19:00 UTC, Djelibeybi approved these changes
Tiny nitpick comment, but also a question: in the comments of the distro-specific build scripts, you mention that XFS, LVM or btrfs are options, but I don't see any handling of the LVM case in `image_cleanup()`, i.e. there's no indication of the activation of VGs or LVs after you loop mount the disk image.

So the question is: what am I missing?  :)

2020-10-19 19:08 UTC, AmedeeBulle commented
> So the question is: what am I missing? :)

The loopback mounts are handled in the [mnt-img.sh](/oracle/ol-sample-scripts/blob/master/oracle-linux-image-tools/bin/mnt-img.sh) script

2020-10-19 19:14 UTC, Djelibeybi commented
> The loopback mounts are handled in the [mnt-img.sh](/oracle/ol-sample-scripts/blob/master/oracle-linux-image-tools/bin/mnt-img.sh) script

I knew I was missing something. 🤓  On that note, _technically_ the file system options are not XFS, LVM or BTRFS but rather XFS with or without LVM and btrfs. LVM use is orthagonal to the actual file system selection. 😛

2020-10-19 19:18 UTC, AmedeeBulle commented
>  On that note, _technically_ the file system options are not XFS, LVM or BTRFS but rather XFS with or without LVM and btrfs. LVM use is orthagonal to the actual file system selection. 😛

Agree, it is there for historical reasons...

2020-10-19 19:21 UTC, Djelibeybi commented
> Agree, it is there for historical reasons...

Which is why I approved the PR regardless. 😄  It's just 6:20am here and my brain appears to be in copy editor mode.

2020-10-19 23:25 UTC, Djelibeybi approved these changes

2020-10-20 08:58 UTC, totalamateurhour approved these changes

2020-10-20 08:58 UTC, merged